INSERT INTO trains (name) VALUES ('1');
INSERT INTO trains (name) VALUES ('R');

INSERT INTO stops (name, train_id) VALUES ('Van Cortlandt Park-242 Street', 1);
INSERT INTO stops (name, train_id) VALUES ('238 Street', 1);
INSERT INTO stops (name, train_id) VALUES ('231 Street', 1);
INSERT INTO stops (name, train_id) VALUES ('Marble Hill-225 Street', 1);
INSERT INTO stops (name, train_id) VALUES ('215 Street', 1);
INSERT INTO stops (name, train_id) VALUES ('207 Street', 1);
INSERT INTO stops (name, train_id) VALUES ('Dyckman Street', 1);
INSERT INTO stops (name, train_id) VALUES ('191 Street', 1);
INSERT INTO stops (name, train_id) VALUES ('181 Street', 1);
INSERT INTO stops (name, train_id) VALUES ('168 Street-Washington Heights', 1);
INSERT INTO stops (name, train_id) VALUES ('157 Street', 1);
INSERT INTO stops (name, train_id) VALUES ('145 Street', 1);
INSERT INTO stops (name, train_id) VALUES ('137 Street-City College', 1);
INSERT INTO stops (name, train_id) VALUES ('125 Street', 1);
INSERT INTO stops (name, train_id) VALUES ('116 Street-Columbia University', 1);
INSERT INTO stops (name, train_id) VALUES ('Cathedral Parkway (110 Street)', 1);
INSERT INTO stops (name, train_id) VALUES ('103 Street', 1);
INSERT INTO stops (name, train_id) VALUES ('96 Street', 1);
INSERT INTO stops (name, train_id) VALUES ('86 Street', 1);
INSERT INTO stops (name, train_id) VALUES ('79 Street', 1);
INSERT INTO stops (name, train_id) VALUES ('72 Street', 1);
INSERT INTO stops (name, train_id) VALUES ('66 Street-Lincoln Center', 1);
INSERT INTO stops (name, train_id) VALUES ('59 Street-Columbus Circle', 1);
INSERT INTO stops (name, train_id) VALUES ('50 Street', 1);
INSERT INTO stops (name, train_id) VALUES ('Times Square-42 Street', 1);
INSERT INTO stops (name, train_id) VALUES ('34 Street-Penn Station', 1);
INSERT INTO stops (name, train_id) VALUES ('28 Street', 1);
INSERT INTO stops (name, train_id) VALUES ('23 Street', 1);
INSERT INTO stops (name, train_id) VALUES ('18 Street', 1);
INSERT INTO stops (name, train_id) VALUES ('14 Street', 1);
INSERT INTO stops (name, train_id) VALUES ('Christopher Street-Sheridan Square', 1);
INSERT INTO stops (name, train_id) VALUES ('Houston Street', 1);
INSERT INTO stops (name, train_id) VALUES ('Canal Street', 1);
INSERT INTO stops (name, train_id) VALUES ('Franklin Street', 1);
INSERT INTO stops (name, train_id) VALUES ('Chambers Street', 1);
INSERT INTO stops (name, train_id) VALUES ('Cortlandt Street TEMPORARILY CLOSED', 1);
INSERT INTO stops (name, train_id) VALUES ('Rector Street', 1);
INSERT INTO stops (name, train_id) VALUES ('South Ferry', 1);

INSERT INTO stops (name, train_id) VALUES ('Forest Hills-71 Avenue', 2);
INSERT INTO stops (name, train_id) VALUES ('67 Avenue', 2);
INSERT INTO stops (name, train_id) VALUES ('63 Drive-Rego Park', 2);
INSERT INTO stops (name, train_id) VALUES ('Woodhaven Boulevard', 2);
INSERT INTO stops (name, train_id) VALUES ('Grand Avenue-Newton', 2);
INSERT INTO stops (name, train_id) VALUES ('Elmhurst Avenue', 2);
INSERT INTO stops (name, train_id) VALUES ('Jackson Heights-Roosevelt Avenue', 2);
INSERT INTO stops (name, train_id) VALUES ('65 Street', 2);
INSERT INTO stops (name, train_id) VALUES ('Northern Boulevard', 2);
INSERT INTO stops (name, train_id) VALUES ('46 Street', 2);
INSERT INTO stops (name, train_id) VALUES ('Steinway Street', 2);
INSERT INTO stops (name, train_id) VALUES ('36 Street', 2);
INSERT INTO stops (name, train_id) VALUES ('Queens Plaza', 2);
INSERT INTO stops (name, train_id) VALUES ('Lexington Avenue', 2);
INSERT INTO stops (name, train_id) VALUES ('5 Avenue', 2);
INSERT INTO stops (name, train_id) VALUES ('57 Street', 2);
INSERT INTO stops (name, train_id) VALUES ('49 Street', 2);
INSERT INTO stops (name, train_id) VALUES ('Times Square-42 Street ', 2);
INSERT INTO stops (name, train_id) VALUES ('34 Street-Herald Square', 2);
INSERT INTO stops (name, train_id) VALUES ('28 Street', 2);
INSERT INTO stops (name, train_id) VALUES ('23 Street', 2);
INSERT INTO stops (name, train_id) VALUES ('14 Street-Union Square', 2);
INSERT INTO stops (name, train_id) VALUES ('8 Street-New York University ', 2);
INSERT INTO stops (name, train_id) VALUES ('Prince Street', 2);
INSERT INTO stops (name, train_id) VALUES ('Canal Street', 2);
INSERT INTO stops (name, train_id) VALUES ('City Hall', 2);
INSERT INTO stops (name, train_id) VALUES ('Cortlandt Street', 2);
INSERT INTO stops (name, train_id) VALUES ('Rector Street', 2);
INSERT INTO stops (name, train_id) VALUES ('Whitehall Street-South Ferry', 2);
INSERT INTO stops (name, train_id) VALUES ('Court Street-Borough Hall', 2);
INSERT INTO stops (name, train_id) VALUES ('Jay Street-MetroTech', 2);
INSERT INTO stops (name, train_id) VALUES ('DeKalb Avenue', 2);
INSERT INTO stops (name, train_id) VALUES ('Atlantic Avenue-Barclays Center', 2);
INSERT INTO stops (name, train_id) VALUES ('Union Street', 2);
INSERT INTO stops (name, train_id) VALUES ('4 Avenue', 2);
INSERT INTO stops (name, train_id) VALUES ('Prospect Avenue', 2);
INSERT INTO stops (name, train_id) VALUES ('25 Street', 2);
INSERT INTO stops (name, train_id) VALUES ('36 Street', 2);
INSERT INTO stops (name, train_id) VALUES ('45 Street', 2);
INSERT INTO stops (name, train_id) VALUES ('53 Street', 2);
INSERT INTO stops (name, train_id) VALUES ('59 Street', 2);
INSERT INTO stops (name, train_id) VALUES ('Bay Ridge Avenue', 2);
INSERT INTO stops (name, train_id) VALUES ('77 Street', 2);
INSERT INTO stops (name, train_id) VALUES ('86 Street', 2);
INSERT INTO stops (name, train_id) VALUES ('Bay Ridge-95 Street', 2);
